# Generated by Django 2.2.12 on 2020-05-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.DateField()),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_servicio', models.IntegerField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
    ]
